### ISSUE TITLE
Can not remove line of text - even after control is de-activated

### ISSUE THREAD

**Issue by JLewis12** [mkoza178/Syr-Digital-Launch#1]
https://test-member.syracuse.com/securepage/dashboard.aspx?sitecode=PS 
I have refreshed and still get same results.

Remove highlighted text from Dashboard page:
![image](https://user-images.githubusercontent.com/26151269/45313543-07ba6780-b4e4-11e8-8558-54d9dde4bb66.png)

Shut off Field and removed Text - Still displays information: (Tested field prior to shut off by adding extra text and refreshing page to verify that this was the correct location for changes. .  Then I deleted all the text entirely since shutting off code did not work. 

![image](https://user-images.githubusercontent.com/26151269/45313590-2a4c8080-b4e4-11e8-8ec2-4656623b1650.png)

**Comment by mkoza178** [comment]
Check now, it's gone. You didn't have to turn it off, just blank out the text: http://prntscr.com/ktm56r
