### ISSUE TITLE
Is it possible to add a Subscription Status to this space. 

### ISSUE THREAD

**Issue by jvanzomeren** [mkoza178/Syr-Digital-Launch#12]
This customer is inactive but there is nothing that says that. 
![screen shot 2018-09-11 at 5 09 47 pm](https://user-images.githubusercontent.com/25616598/45388265-7aac0700-b5e6-11e8-9e4f-58b79345ae54.png)

**Comment by mkoza178** [comment]
Depends what you would like it to say and where. Can you give me a mock?

**Comment by mkoza178** [comment]
Current Status:
L (Active)
S (Stopped)
V (Not Active) 

Bold the text as well.

**Comment by mkoza178** [comment]
TFS [39890](https://tfs.marketingg2.com/tfs/DefaultCollection/Proj_Mgmnt/_workitems#_a=edit&id=39890)

**Comment by mkoza178** [comment]
This is ready to Test

**Comment by jvanzomeren** [comment]
test looks great thanks!
