### ISSUE TITLE
Test - payment.aspx - payment options not visible when selected

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Syr-Digital-Launch#17]
On the test Portland member page, when making a payment and a payment option is selected, the text is not visible.  This is working correctly on the test Syracuse page.  Screen shots below:

Portland:
![image](https://user-images.githubusercontent.com/25667903/46096247-54f53500-c184-11e8-8783-ee2520df7cba.png)

Syracuse:
![image](https://user-images.githubusercontent.com/25667903/46096294-722a0380-c184-11e8-80d1-9d5c3cc5b3df.png)

**Comment by mkoza178** [comment]
TFS [39985 ](https://tfs.marketingg2.com/tfs/web/wi.aspx?pcguid=ebe56fba-ddfa-44d6-8d95-bad792ec2f79&id=39985)

**Comment by mkoza178** [comment]
This is resolved. Check it out.
