### ISSUE TITLE
Active sub error on start 

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Syr-Digital-Launch#2]
Attempting to start a subscription at 413 Fremont Rd returns the error "An account already exists with this address".  Account is stopped in DTI (has been stopped since February of 2018) and shows stopped in SubCon as well.  Should be able to start a subscription at the address without error.  Screen shots below.

**Error on start:**
![image](https://user-images.githubusercontent.com/25667903/45325068-867bc880-b515-11e8-83dc-1e7c91cdb52a.png)

**Status shown in SubCon**
![image](https://user-images.githubusercontent.com/25667903/45325106-a7441e00-b515-11e8-8ce6-d7aaa68ddae7.png)

**Comment by mkoza178** [comment]
Hey,

So there's two checks that occur when submitting a start:
Active sub check against OI database 
Active sub check against G2suite database

This start is being caught by the G2Suite database one which runs a check against: Starts that have occurred for an address in the past 15 days. We can get rid of this or change that 15 day value to be lower if you want.
